include theme.conf

# font_family      JetBrainsMono Nerd Font
font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 10.0

update_check_interval 0
allow_remote_control yes
confirm_os_window_close 0

# reverse video cursor
cursor none

window_padding_width 1 1 1 1

# Nerd Fonts symbols (requires ttf-nerd-fonts-symbols)
symbol_map U+E000-U+E00D Symbols Nerd Font Mono
symbol_map U+E0A0-U+E0A2,U+E0B0-U+E0B3 Symbols Nerd Font Mono
symbol_map U+E0A3,U+E0B4-U+E0C8,U+E0CC-U+E0D2,U+E0D4 Symbols Nerd Font Mono
symbol_map U+E0CA,U+E0D0 Symbols Nerd Font Mono
symbol_map U+E5FA-U+E62F Symbols Nerd Font Mono
symbol_map U+E700-U+E7C5 Symbols Nerd Font Mono
symbol_map U+F000-U+F2E0 Symbols Nerd Font Mono
symbol_map U+E200-U+E2A9 Symbols Nerd Font Mono
symbol_map U+F400-U+F4A8,U+2665,U+26A1,U+F27C Symbols Nerd Font Mono
symbol_map U+F300-U+F313 Symbols Nerd Font Mono
symbol_map U+23FB-U+23FE,U+2B58 Symbols Nerd Font Mono
symbol_map U+F500-U+FD46 Symbols Nerd Font Mono
symbol_map U+F0001-U+F1AF0 Symbols Nerd Font Mono


