# userspawn runs an executable, you specify, when a user logs in. This could be a bash script, or anything else you want!
# This can be used to launch a user instance of your init system.

# userspawn works in conjunction with (e)logind, and hence, dbus. It listens for users being added or removed.
# For every user addition, a new cgroup is created for that user and userspawn config is spawned into that cgroup.
# Upon user removal, that cgroup is then cleaned up, as triggered by (e)logind.


# The options provided here are not checked for validity, they are just ran for your user. If you cook them, your personal dinit process will be cooked.
# These configs are unique to each user, one config does not affect another user.

# Binary to execute. Change if in a different location.
binary = "/usr/bin/dinit"

# Add arguments one by one, for example ["--user", "--services-dir", "/home/myuser/.config/dinit.d"].
dinit_arguments = ["--user"] 

# Enables verbose debugging options. It will flood logs, in catlog.
verbose_debug = false

