CompileFlags:
  Add:
    - -Wall
    - -Wextra
    - -Wshadow
    - -Wno-unused-parameter

# Diagnostic section specific for C/CPP
Diagnostics:
  UnusedIncludes: Strict
  MissingIncludes: Strict

Hover:
  ShowAKA: true

InlayHints:
  Enabled: true
  ParameterNames: true
  DeducedTypes: true
  Designators: true
  BlockEnd: true

Completion:
  AllScopes: true
