general {
    hide_cursor        = true
    ignore_empty_input = true
    grace              = 2
}

background {
    monitor     =
    path        = screenshot
    blur_passes = 3
    blur_size   = 7
    brightness  = 0.5
    vibrancy    = 0.1696
}

# clock
label {
    monitor     =
    text        = $TIME
    font_size   = 72
    font_family = JetBrainsMono Nerd Font
    color       = rgb(248, 248, 242)
    position    = 0, 160
    halign      = center
    valign      = center
}

# date
label {
    monitor     =
    text        = cmd[update:60000] date +"%A, %d %B %Y"
    font_size   = 18
    font_family = JetBrainsMono Nerd Font
    color       = rgb(189, 147, 249)
    position    = 0, 90
    halign      = center
    valign      = center
}

# user
label {
    monitor     =
    text        = $USER
    font_size   = 14
    font_family = JetBrainsMono Nerd Font
    color       = rgb(98, 114, 164)
    position    = 0, 30
    halign      = center
    valign      = center
}

# password input
input-field {
    monitor           =
    size              = 20%, 5%
    outline_thickness = 3
    inner_color       = rgba(40, 42, 54, 0.8)
    outer_color       = rgba(189, 147, 249, 1.0) rgba(255, 121, 198, 1.0) 45deg
    check_color       = rgba(80, 250, 123, 1.0)
    fail_color        = rgba(255, 85, 85, 1.0) rgba(255, 121, 198, 1.0) 40deg
    fail_color        = rgba(255, 85, 85, 1.0) rgb(255, 85, 0, 1.0) 40deg
    font_color        = rgb(248, 248, 242)
    font_family       = JetBrainsMono Nerd Font
    placeholder_text  = <i>Password</i>
    fade_on_empty     = true
    rounding          = 10
    position          = 0, -30
    halign            = center
    valign            = center
}

# fail message
label {
    monitor     =
    text        = $FAIL
    font_size   = 12
    font_family = JetBrainsMono Nerd Font
    color       = rgb(255, 85, 85)
    position    = 0, -90
    halign      = center
    valign      = center
}
