general {
    hide_cursor        = true
    ignore_empty_input = true
}

background {
    monitor     =
    # path        = cmd[update:2000] ~/.config/hypr/scripts/random_img_path.sh ~/Pictures/Wallpapers/
    path        = ~/Pictures/Wallpapers/dracula_1.jpg
    blur_passes = 3
    blur_size   = 7
    brightness  = 0.5
    vibrancy    = 0.1696
}

# clock
label {
    monitor     =
    text        = $TIME
    font_size   = 72
    font_family = JetBrainsMono Nerd Font
    color       = rgba(248, 248, 242, 1.0)
    position    = 0, 160
    halign      = center
    valign      = center
}

# date
label {
    monitor     =
    text        = cmd[update:60000] date +"%A, %d %B %Y"
    font_size   = 18
    font_family = JetBrainsMono Nerd Font
    color       = rgba(189, 147, 249, 1.0)
    position    = 0, 90
    halign      = center
    valign      = center
}

# user
label {
    monitor     =
    text        = $USER
    font_size   = 14
    font_family = JetBrainsMono Nerd Font
    color       = rgba(80, 250, 123, 1.0)
    position    = 0, 30
    halign      = center
    valign      = center
}

image {
    monitor     =
    # path        = cmd[update:2000] ~/.config/hypr/scripts/cover_art.sh
    path        = /home/wasi/Pictures/Pfps/72d3618768190e82e138bae415eebf96.png
    size        = 200
    rounding    = 10
    border_size = 2
    border_color = rgba(189, 147, 249, 1.0)
    position    = 0, -200
    halign      = center
    valign      = center
}

# password input
input-field {
    monitor           =
    size              = 20%, 5%
    outline_thickness = 3
    inner_color       = rgba(40, 42, 54, 0.8)
    outer_color       = rgba(189, 147, 249, 1.0) rgba(255, 121, 198, 1.0) 45deg
    check_color       = rgba(80, 250, 123, 1.0)
    fail_color        = rgba(255, 85, 85, 1.0) rgba(255, 85, 0, 1.0) 40deg
    font_color        = rgba(248, 248, 242, 1.0)
    font_family       = JetBrainsMono Nerd Font
    placeholder_text  = <i>Password</i>
    fade_on_empty     = true
    rounding          = 10
    position          = 0, -30
    halign            = center
    valign            = center
}

# fail message
label {
    monitor     =
    text        = $FAIL
    font_size   = 12
    font_family = JetBrainsMono Nerd Font
    color       = rgba(255, 85, 85, 1.0)
    position    = 0, -90
    halign      = center
    valign      = center
}
