general {
    lock_cmd               = pidof hyprlock || hyprlock
    unlock_cmd             =
    before_sleep_cmd       = loginctl lock-session
    after_sleep_cmd        = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
    ignore_dbus_inhibit    = false
    ignore_systemd_inhibit = false
}

# dim at 4 min
listener {
    timeout    = 240
    on-timeout = brightnessctl set 15%
    on-resume  = brightnessctl set 30%
}

# lock at 5 min
listener {
    timeout    = 300
    on-timeout = loginctl lock-session
}

# screen off at 6 min
listener {
    timeout    = 360
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume  = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# BUG: turns laptop off if i put hibernate
# hybrid-sleep at 15 min
listener {
    timeout    = 900
    on-timeout = loginctl hybrid-sleep
}
